obs: use stable source file instead of git repo

diff --git a/obs/home:metakcahura:arch-deepin/deepin-vte-plus/PKGBUILD b/obs/home:metakcahura:arch-deepin/deepin-vte-plus/PKGBUILD
--- a/obs/home:metakcahura:arch-deepin/deepin-vte-plus/PKGBUILD
+++ b/obs/home:metakcahura:arch-deepin/deepin-vte-plus/PKGBUILD
@@ -5,6 +5,7 @@ pkgname=deepin-vte-plus
 _pkgname=vte
 pkgver=0.28.2
 pkgrel=8
+epoch=1
 pkgdesc="Virtual Terminal Emulator widget for use with GTK2 - with several patches"
 arch=('i686' 'x86_64')
 license=('GPL3')
@@ -15,45 +16,40 @@ makedepends=('deepin-pygtk' 'intltool' 'gobject-introspection' 'pygobject2-devel
 provides=('vte=0.28.2')
 conflicts=('vte')
 options=('!libtool' '!emptydirs')
-
-_site="http://test.packages.linuxdeepin.com/deepin/pool/main/v"
-source=("${_site}/${_pkgname}/${_pkgname}_${pkgver}.orig.tar.xz"
-        "${_site}/${_pkgname}/${_pkgname}_${pkgver}-6deepin7~saucy.debian.tar.gz")
+_mirror="https://ftp.fau.de/deepin/pool/main"
+source=("${_mirror}/v/${_pkgname}/${_pkgname}_${pkgver}.orig.tar.xz"
+		"${_mirror}/v/${_pkgname}_${pkgver}-6deepin7~saucy.debian.tar.gz")
 sha256sums=('ee52b91ecab31d0a64399896ce0c3515e579ea8ac212a00eb9b0895c58f001fe'
-	    'b63a344541f0feebddac0232a8d7196d22d4819ec32cbd6cb39e33b2ba50e940')
+			'b63a344541f0feebddac0232a8d7196d22d4819ec32cbd6cb39e33b2ba50e940')
 
 prepare() {
-
-# unzip patches
-  cd "$srcdir/"
-  tar -xf vte_0.28.2-6deepin7~saucy.debian.tar.gz
-
-# apply patches
-  cd "$srcdir/"
-
-  patchdir=$srcdir/debian/patches
-  for f in $(< $patchdir/series); do
-    echo "==> patching: ${f##*/}"
-    # ignore error if patch again
-    patch -Np1 -i $patchdir/$f || echo '==> patch error: ${f##*/}'
-  done
-
+	patchdir=$srcdir/debian/patches
+	for f in $(< $patchdir/series); do
+	echo "==> patching: ${f##*/}"
+	# ignore error if patch again
+	patch -Np1 -i $patchdir/$f || echo '==> patch error: ${f##*/}'
+	done
 }
 
 build() {
-  cd "$srcdir/"
-  #warning: type-punning to incomplete type might break strict-aliasing rules
-  export CFLAGS="$CFLAGS -fno-strict-aliasing"
-  export PYTHON="/usr/bin/python2"
-  ./configure --prefix=/usr --sysconfdir=/etc \
-    --libexecdir=/usr/lib/vte                 \
-    --localstatedir=/var --disable-static     \
-    --enable-introspection --with-gtk=2.0
-  make
+	cd "$srcdir"
+	
+	#warning: type-punning to incomplete type might break strict-aliasing rules
+	export CFLAGS="$CFLAGS -fno-strict-aliasing"
+	export PYTHON="/usr/bin/python2"
+
+	./configure --prefix=/usr --sysconfdir=/etc \
+		--libexecdir=/usr/lib/vte \
+		--localstatedir=/var \
+		--disable-static \
+		--enable-introspection \
+		--with-gtk=2.0
+	make
 }
 
 package(){
-  cd "$srcdir/"
-  make DESTDIR="$pkgdir" install
-  rm -f "$pkgdir/usr/lib/vte/gnome-pty-helper"
+	cd "$srcdir"
+
+	make DESTDIR="$pkgdir" install
+	rm -f "$pkgdir"/usr/lib/vte/gnome-pty-helper
 }
diff --git a/obs/home:metakcahura:arch-deepin/go-gocheck/PKGBUILD b/obs/home:metakcahura:arch-deepin/go-gocheck/PKGBUILD
--- a/obs/home:metakcahura:arch-deepin/go-gocheck/PKGBUILD
+++ b/obs/home:metakcahura:arch-deepin/go-gocheck/PKGBUILD
@@ -3,19 +3,16 @@
 
 _pkgname=golang-gocheck
 pkgname=go-gocheck
-_pkgverbase=0.0
-_pkgvergit=20131118+85
-_pkgver=${_pkgverbase}~bzr${_pkgvergit}
-pkgver=${_pkgverbase}.${_pkgvergit/+/.}
+pkgver=0.0~bzr20131118+85
 pkgrel=8
 pkgdesc='Richer testing framework for Go libraries and applications to use'
 arch=('any')
 url="http://labix.org/gocheck"
 license=('BSD')
 replaces=('golang-gocheck')
-site="http://packages.linuxdeepin.com/deepin/pool/main/g"
-source=("${site}/${_pkgname}/${_pkgname}_${_pkgver}.orig.tar.gz"
-        "${site}/${_pkgname}/${_pkgname}_${_pkgver}-6.debian.tar.gz")
+_mirror="https://ftp.fau.de/deepin/pool/main"
+source=("${_mirror}/g/${_pkgname}/${_pkgname}_${pkgver}.orig.tar.gz"
+        "${_mirror}/g/${_pkgname}/${_pkgname}_${pkgver}-6.debian.tar.gz")
 sha256sums=('71ba0752af3cd04a42a95ef68c098d251430281c8461272df259d52d6092f7da'
             '3a50e3d0c4ccb9397f13c30a6f057187c419e3b362c6b90767ed0bec049108fc')
 
@@ -23,19 +20,19 @@ _gobuild_dir="${_pkgname}-build"
 _gopkg="launchpad.net/gocheck"
 
 prepare() {
-  cd "${_pkgname}-${_pkgver}"
+	cd "${_pkgname}-${pkgver}"
 
-  # apply patches
-  patchdir="${srcdir}"/debian/patches
-  for f in $(< "${patchdir}"/series); do
-    echo "==> patching: ${f##*/}"
-    # ignore error if patch again
-    patch -Np1 -i $patchdir/$f || echo '==> patch error: ${f##*/}'
-  done
+	# apply patches
+	patchdir="${srcdir}"/debian/patches
+	for f in $(< "${patchdir}"/series); do
+	echo "==> patching: ${f##*/}"
+	# ignore error if patch again
+	patch -Np1 -i $patchdir/$f || echo '==> patch error: ${f##*/}'
+	done
 
-  cd "${srcdir}"
-  mkdir -p "${_gobuild_dir}"/src/"${_gopkg}"
-  cp -r "${_pkgname}-${_pkgver}"/* "${_gobuild_dir}"/src/"${_gopkg}"/
+	cd "${srcdir}"
+	mkdir -p "${_gobuild_dir}"/src/"${_gopkg}"
+	cp -r "${_pkgname}-${pkgver}"/* "${_gobuild_dir}"/src/"${_gopkg}"/
 }
 
 #build() {
@@ -43,8 +40,8 @@ prepare() {
 #}
 
 package() {
-  depends=('go')
+	depends=('go')
 
-  mkdir -p "${pkgdir}"/usr/lib/go/site/src
-  cp -r "${_gobuild_dir}"/src/* "${pkgdir}"/usr/lib/go/site/src/
+	mkdir -p "${pkgdir}"/usr/lib/go/site/src
+	cp -r "${_gobuild_dir}"/src/* "${pkgdir}"/usr/lib/go/site/src/
 }
