fix pkgbuild issues

diff --git a/pkgbuild/deepin-vte/PKGBUILD b/pkgbuild/deepin-vte/PKGBUILD
--- a/pkgbuild/deepin-vte/PKGBUILD
+++ b/pkgbuild/deepin-vte/PKGBUILD
@@ -4,7 +4,7 @@
 pkgname=deepin-vte
 _pkgname=vte
 pkgver=0.28.2
-_pkgver=0.28.2-6deepin7~saucy
+_pkgver=0.28.2
 pkgrel=8
 epoch=1
 pkgdesc="Virtual Terminal Emulator widget for use with GTK2 - with several patches"
@@ -28,7 +28,7 @@ prepare() {
   for f in $(< "${patchdir}"/series); do
     echo "==> patching: ${f##*/}"
     # ignore error if patch again
-    patch -Np1 -i "${patchdir}"/$f || echo '==> patch error: ${f##*/}'
+    patch -Np1 -i "${patchdir}/${f}" || echo "==> patch error: ${f##*/}"
   done
 }
 
diff --git a/template/deepin-pygtk/PKGBUILD.in b/template/deepin-pygtk/PKGBUILD.in
--- a/template/deepin-pygtk/PKGBUILD.in
+++ b/template/deepin-pygtk/PKGBUILD.in
@@ -4,7 +4,7 @@
 pkgname=deepin-pygtk
 _pkgname=pygtk
 pkgver=@PKGVER_FIXED@
-_pkgver=@PKGVER@
+_pkgver=@PKGVER_SRC@
 pkgrel=6
 pkgdesc="Python bindings for the GTK widget set - with patches to fix memory leak for deepin-ui"
 arch=('i686' 'x86_64')
@@ -25,22 +25,18 @@ provides=("${_pkgname}=2.24.0")
 conflicts=("${_pkgname}")
 
 prepare() {
-
-  # unzip patches
-  cd "$srcdir/"
-  tar -xf ${_pkgname}_${_pkgver}-4~saucy.debian.tar.gz
-
   cd "${_pkgname}-${_pkgver}"
+
   # apply python27 patch
   # https://bugzilla.gnome.org/show_bug.cgi?id=623965
   patch -Np1 -i "${srcdir}/python27.patch"
 
   # apply deepin patches
-  patchdir=${srcdir}/debian/patches
-  for f in $(< ${patchdir}/series); do
+  patchdir="${srcdir}"/debian/patches
+  for f in $(< "${patchdir}"/series); do
     echo "==> patching: ${f##*/}"
     # ignore error if patch again
-    patch -Np1 -i ${patchdir}/${f} || echo '==> patch error: ${f##*/}'
+    patch -Np1 -i "${patchdir}/${f}" || echo "==> patch error: ${f##*/}"
   done
 
 }
