pygtk, ui, vte: apply advice from flu

diff --git a/deepin-pygtk-fix/PKGBUILD b/deepin-pygtk-fix/PKGBUILD
--- a/deepin-pygtk-fix/PKGBUILD
+++ b/deepin-pygtk-fix/PKGBUILD
@@ -1,7 +1,8 @@
 # Maintainer: Xu Fasheng <fasheng.xu[AT]gmail.com>
+# Contributor: flu
 
 pkgname=deepin-pygtk-fix
-_realname=pygtk
+_pkgname=pygtk
 pkgver=2.24.0
 pkgrel=3
 pkgdesc="Python bindings for the GTK widget set - with patches to fix memory leak for deepin-ui"
@@ -10,8 +11,8 @@ url="http://www.pygtk.org/"
 license=('LGPL')
 depends=('libglade' 'python2-cairo' 'pygobject')
 optdepends=('python2-numpy')
-provides=('pygtk=2.24.0')
-conflicts=('pygtk')
+provides=("${_pkgname}=2.24.0")
+conflicts=("${_pkgname}")
 
 _pkgsite="http://packages.linuxdeepin.com"
 # _pkgsite="http://mirrors.ustc.edu.cn" # candidate server
@@ -23,33 +24,35 @@ md5sums=('d27c7f245a9e027f6b6cd9acb7468e36'
          '12acfacd26f19c504a0a2d0edeb66121'
          '9e513bdf36ba873030182d9d5092d08b')
 
-build() {
-    #unzip patches
-    cd "$srcdir/"
+prepare() {
+    # unzip patches
+    cd "${srcdir}/"
     tar -xf ${_patchfile}
 
-    cd "${_realname}-${pkgver}"
+    cd "${_pkgname}-${pkgver}"
 
-    #apply python27 patch
-    #https://bugzilla.gnome.org/show_bug.cgi?id=623965
+    # apply python27 patch
+    # https://bugzilla.gnome.org/show_bug.cgi?id=623965
     patch -Np1 -i "${srcdir}/python27.patch"
 
-    #apply deepin patches
-    patchdir=${srcdir}/debian/patches
+    # apply deepin patches
+    patchdir="${srcdir}/debian/patches"
     for f in `cat ${patchdir}/series`; do
         echo "==> patching: ${f##*/}"
         # ignore error if patch again
-        patch -Np1 -i ${patchdir}/${f} || echo '==> patch error: ${f##*/}'
+        patch -Np1 -i "${patchdir}/${f}" || echo '==> patch error: ${f##*/}'
     done
+}
 
+build() {
+    cd "${srcdir}/${_pkgname}-${pkgver}"
     PYTHON=/usr/bin/python2 ./configure --prefix=/usr
     make
 }
 
 package() {
-  cd "${srcdir}/${_realname}-${pkgver}"
-  make DESTDIR="${pkgdir}" install
-  install -m644 gtk/gtk-extrafuncs.defs "${pkgdir}/usr/share/pygtk/2.0/defs/"
-
-  sed -i -e 's#env python$#env python2#' "${pkgdir}"/usr/lib/pygtk/2.0/{,demos/}*.py
+    cd "${srcdir}/${_pkgname}-${pkgver}"
+    make DESTDIR="${pkgdir}" install
+    install -m644 gtk/gtk-extrafuncs.defs "${pkgdir}/usr/share/pygtk/2.0/defs/"
+    sed -i 's=\(^#! */usr/bin.*\)python=\1python2=' "${pkgdir}"/usr/lib/pygtk/2.0/{,demos/}*.py
 }
diff --git a/deepin-vte-plus/PKGBUILD b/deepin-vte-plus/PKGBUILD
--- a/deepin-vte-plus/PKGBUILD
+++ b/deepin-vte-plus/PKGBUILD
@@ -1,4 +1,5 @@
 # Maintainer: Xu Fasheng <fasheng.xu[AT]gmail.com>
+# Contributo: flu
 
 pkgname=deepin-vte-plus
 _pkgname=vte
@@ -10,8 +11,8 @@ url="https://developer.gnome.org/vte/"
 license=('GPL3')
 depends=('gtk2')
 makedepends=('pygtk' 'intltool' 'gobject-introspection' 'pygobject2-devel')
-provides=('vte=0.28.2')
-conflicts=('vte')
+provides=("${_pkgname}=0.28.2")
+conflicts=("${_pkgname}")
 options=('!libtool' '!emptydirs')
 
 _patchsite="http://packages.linuxdeepin.com"
@@ -21,21 +22,24 @@ source=(http://ftp.gnome.org/pub/GNOME/sources/vte/0.28/vte-$pkgver.tar.xz
 md5sums=('497f26e457308649e6ece32b3bb142ff'
          '55a179adbb01e0060981eb22294e015c')
 
-build() {
+prepare() {
     #unzip patches
-    cd "$srcdir/"
+    cd "${srcdir}/"
     tar -xf vte_0.28.2-6deepin6.debian.tar.gz
 
-    cd "$_pkgname-$pkgver"
+    cd "${_pkgname}-${pkgver}"
 
     #apply patches
     patchdir=$srcdir/debian/patches
     for f in `cat $patchdir/series`; do
         echo "==> patching: ${f##*/}"
         # ignore error if patch again
-        patch -Np1 -i $patchdir/$f || echo '==> patch error: ${f##*/}'
+        patch -Np1 -i "${patchdir}/${f}" || echo '==> patch error: ${f##*/}'
     done
+}
 
+build() {
+    cd "${srcdir}/${_pkgname}-${pkgver}"
     #warning: type-punning to incomplete type might break strict-aliasing rules
     export CFLAGS="$CFLAGS -fno-strict-aliasing"
     export PYTHON="/usr/bin/python2"
@@ -47,7 +51,7 @@ build() {
 }
 
 package(){
-    cd "$srcdir/$_pkgname-$pkgver"
-    make DESTDIR="$pkgdir" install
-    rm -f "$pkgdir/usr/lib/vte/gnome-pty-helper"
+    cd "${srcdir}/${_pkgname}-${pkgver}"
+    make DESTDIR="${pkgdir}" install
+    rm -f "${pkgdir}/usr/lib/vte/gnome-pty-helper"
 }
